<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>ELTE.TravelAgency.Admin</RootNamespace>
    <Authors>Máté Cserép</Authors>
    <Company>ELTE Eötvös Loránd University, Faculty of Informatics</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TravelAgency.Shared\TravelAgency.Shared.csproj" />
  </ItemGroup>

</Project>
