# Generated by Django 5.0.6 on 2024-06-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGOEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('volonteer_num', models.IntegerField(default=0)),
                ('avg_rating', models.IntegerField(default=0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
            ],
        ),
    ]
