# Generated by Django 5.0.6 on 2024-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoentity',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ngoentity',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
