# Generated by Django 5.0.6 on 2025-01-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngo", "0002_alter_ngoentity_avg_rating_and_more"),
        ("shared", "0003_alter_team_name_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngoentity",
            name="ngo_profile_gallery",
            field=models.ManyToManyField(
                blank=True, related_name="ngo_gallery", to="shared.photo"
            ),
        ),
    ]
