# Generated by Django 5.0.6 on 2025-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_ngoentity_ngo_profile_gallery'),
        ('shared', '0005_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoentity',
            name='focus_teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='ngo_focus_teams', to='shared.team'),
        ),
        migrations.AddField(
            model_name='ngoentity',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ngoentity',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
