# Generated by Django 5.0.6 on 2025-01-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_ngoentity_focus_teams_ngoentity_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('facebook', 'Facebook')], max_length=50)),
                ('url', models.URLField()),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='ngo.ngoentity')),
            ],
        ),
    ]
