# Generated by Django 5.0.6 on 2025-01-29 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0005_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('TikTok', 'TikTok'), ('Facebook', 'Facebook')], max_length=50),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_type', models.CharField(choices=[('Phone', 'Phone'), ('E-mail', 'E-mail')], max_length=20)),
                ('contact_info', models.CharField(max_length=100)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ngo.ngoentity')),
            ],
        ),
    ]
