# Generated by Django 5.0.6 on 2025-01-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_alter_socialmedia_platform_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_options', to='ngo.ngoentity'),
        ),
    ]
