# Generated by Django 5.1.6 on 2025-02-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0009_contact_user_socialmedia_user_alter_contact_ngo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoentity',
            name='profile_image_url',
        ),
    ]
