# Generated by Django 5.1.6 on 2025-07-23 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0011_ngoentity_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoentity',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ngoentity',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ngoentity',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ngoentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngoentity',
            name='offerings',
            field=models.CharField(blank=True, help_text='Comma-separated list of offerings', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ngoentity',
            name='operating_countries',
            field=models.TextField(blank=True, help_text='Countries where the organization operates (comma-separated)', null=True),
        ),
        migrations.AddField(
            model_name='ngoentity',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ngoentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ngoentity',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('TikTok', 'TikTok'), ('Facebook', 'Facebook'), ('YouTube', 'YouTube')], max_length=50),
        ),
    ]
