# Generated by Django 5.0.6 on 2025-01-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.IntegerField(
                choices=[
                    (1, "INTO_THE_HEIGHTS"),
                    (2, "MARINES"),
                    (3, "GREEN_CITIES"),
                    (4, "ANCIENT_FORESTS_FOREVAA"),
                    (5, "SURPRISE ME"),
                ]
            ),
        ),
    ]
