# Generated by Django 5.0.6 on 2025-01-16 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_photo_event"),
        ("ngo", "0002_alter_ngoentity_avg_rating_and_more"),
        ("shared", "0002_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.IntegerField(
                choices=[
                    (1, "INTO THE HEIGHTS"),
                    (2, "MARINES"),
                    (3, "GREEN CITIES"),
                    (4, "ANCIENT FORESTS FOREVAA"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField()),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_gallery_photos",
                        to="events.event",
                    ),
                ),
                (
                    "ngo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngo_profile_photos",
                        to="ngo.ngoentity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
