# Generated by Django 5.0.6 on 2025-01-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0003_alter_team_name_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="event",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="ngo",
        ),
    ]
