# Generated by Django 5.0.6 on 2025-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_remove_photo_event_remove_photo_ngo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
