# Generated by Django 5.0.6 on 2025-01-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='competences',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
