# Generated by Django 5.0.6 on 2025-01-27 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_ngoentity_focus_teams_ngoentity_history_and_more'),
        ('shared', '0006_competences_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_by_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_personal_gallery', to='ngo.ngoentity'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_personal_gallery', to=settings.AUTH_USER_MODEL),
        ),
    ]
