# Generated by Django 5.0.6 on 2025-01-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_photo_photo_by_ngo_photo_photo_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('xpGiven', models.IntegerField()),
                ('logo', models.URLField(blank=True)),
            ],
        ),
    ]
