# Generated by Django 5.0.6 on 2025-01-27 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_delete_achievements_alter_event_achievements'),
        ('shared', '0008_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='event_related_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_gallery', to='events.event'),
        ),
    ]
