# Generated by Django 5.0.6 on 2025-01-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_alter_photo_photo_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='large_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
