# Generated by Django 5.0.6 on 2025-02-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_rename_image_photo_large_image_photo_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='name',
            new_name='type',
        ),
    ]
