# Generated by Django 5.1.6 on 2025-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0013_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
