# Generated by Django 5.0.6 on 2025-01-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="impact_gallery",
        ),
        migrations.RemoveField(
            model_name="petition",
            name="impact_gallery",
        ),
        migrations.DeleteModel(
            name="UserPhoto",
        ),
    ]
