# Generated by Django 5.0.6 on 2025-01-20 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_friends_applied'),
        ('user', '0002_remove_donation_impact_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('saved', 'Saved')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usereventinteraction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'saved'), _negated=True), fields=('user', 'event'), name='unique_application_status_per_user_event'),
        ),
    ]
