# Generated by Django 5.0.6 on 2025-01-27 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_achievements_logo'),
        ('shared', '0006_competences_logo'),
        ('user', '0003_usereventinteraction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='applied_events',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='enrolled_events',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='saved_events',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gained_achievements',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_gained_achievements', to='events.achievements'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_profile_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by_user', to='shared.photo'),
        ),
    ]
