# Generated by Django 5.0.6 on 2025-01-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customuser_applied_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_profile_gallery',
        ),
    ]
