# Generated by Django 5.0.6 on 2025-01-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_achievements'),
        ('user', '0006_remove_customuser_age_customuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gained_achievements',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_gained_achievements', to='shared.achievements'),
        ),
    ]
