# Generated by Django 5.0.6 on 2025-01-29 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_ngoentity_focus_teams_ngoentity_history_and_more'),
        ('user', '0007_alter_customuser_gained_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='reviewed_rating',
            new_name='review_rating',
        ),
        migrations.AlterField(
            model_name='userreview',
            name='date_reviewed',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='reviewed_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ngo.ngoentity'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='reviewed_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.store'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userreview',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('reviewed_ngo__isnull', False), ('reviewed_store__isnull', True)), models.Q(('reviewed_ngo__isnull', True), ('reviewed_store__isnull', False)), _connector='OR'), name='only_one_reviewed_entity'),
        ),
    ]
