# Generated by Django 5.0.6 on 2025-01-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0005_socialmedia'),
        ('user', '0008_rename_reviewed_rating_userreview_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='reviewed_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='ngo.ngoentity'),
        ),
    ]
