# Generated by Django 5.0.6 on 2025-01-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userreview_reviewed_ngo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='friends_that_donated',
            new_name='donators_count',
        ),
        migrations.AddField(
            model_name='donation',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
