# Generated by Django 5.0.6 on 2025-01-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_friends_that_donated_donation_donators_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='level',
        ),
        migrations.AddField(
            model_name='usergoal',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.TextField(choices=[('Modern dragons', 'Modern dragons'), ("Forest's dead man", "Forest's dead man"), ('Cuties', 'Cuties'), ('Alien predator', 'Alien predator')]),
        ),
    ]
