# Generated by Django 5.0.6 on 2025-01-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_goal_level_usergoal_level_alter_goal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.TextField(blank=True, choices=[('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Legendary', 'Legendary')], null=True),
        ),
    ]
