# Generated by Django 5.0.6 on 2025-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_goal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='causes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expectations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
