# Generated by Django 5.0.6 on 2025-02-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_experiencedevelopmentstage_customuser_current_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_stage',
        ),
    ]
