# Generated by Django 5.0.6 on 2025-02-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_customuser_current_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExperienceDevelopmentStage',
        ),
    ]
