# Generated by Django 5.0.6 on 2025-02-14 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_delete_experiencedevelopmentstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceDevelopmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Eco Pioneer', 'Eco Pioneer'), ('Biosphere Guardian', 'Biosphere Guardian'), ("Gaia's Emissary", "Gaia's Emissary"), ('Planet Healer', 'Planet Healer'), ('Cosmic Steward', 'Cosmic Steward')], max_length=50)),
                ('xp_required', models.IntegerField(default=0)),
                ('next_stage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_stage_relation', to='user.experiencedevelopmentstage')),
                ('previous_stage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_stage_relation', to='user.experiencedevelopmentstage')),
            ],
        ),
    ]
