# Generated by Django 5.0.6 on 2025-02-15 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_team_event_focus_teams'),
        ('user', '0018_customuser_current_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='usereventinteraction',
            name='unique_application_status_per_user_event',
        ),
        migrations.AddConstraint(
            model_name='usereventinteraction',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_application_status_per_user_event'),
        ),
        migrations.AddField(
            model_name='usersavedevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='usersavedevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersavedevent',
            unique_together={('user', 'event')},
        ),
    ]
