# Generated by Django 5.0.6 on 2025-02-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_usersavedevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRRDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bic', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient_address', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usereventinteraction',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('completed', 'Completed')], max_length=10),
        ),
    ]
