# Generated by Django 5.0.6 on 2025-02-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_trrdonation_alter_usereventinteraction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedevents',
            name='event',
        ),
        migrations.RemoveField(
            model_name='completedevents',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='saved_donations_by_users',
        ),
        migrations.DeleteModel(
            name='TRRDonation',
        ),
        migrations.DeleteModel(
            name='CompletedEvents',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
