# Generated by Django 5.1.6 on 2025-02-18 23:11

import django.core.validators
import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_completedevents_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_in_stage', to='user.experiencedevelopmentstage'),
        ),
        migrations.CreateModel(
            name='GoalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_xp', models.PositiveIntegerField()),
                ('max_xp', models.PositiveIntegerField()),
                ('stage_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='user.goal')),
            ],
            options={
                'unique_together': {('goal', 'min_xp', 'max_xp')},
            },
        ),
        migrations.AddField(
            model_name='usergoal',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.goalstage'),
        ),
    ]
