# Generated by Django 5.1.6 on 2025-02-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_customuser_current_stage_goalstage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_stage',
        ),
    ]
