# Generated by Django 5.1.6 on 2025-02-18 23:16

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_customuser_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_in_stage', to='user.experiencedevelopmentstage'),
        ),
    ]
