# Generated by Django 5.1.6 on 2025-02-19 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_customuser_current_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goalstage',
            name='max_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goalstage',
            name='min_xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
