# Generated by Django 5.1.6 on 2025-02-19 21:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_customuser_following_alter_goalstage_max_xp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencedevelopmentstage',
            name='next_stage',
        ),
        migrations.RemoveField(
            model_name='experiencedevelopmentstage',
            name='previous_stage',
        ),
        migrations.RemoveField(
            model_name='experiencedevelopmentstage',
            name='xp_required',
        ),
        migrations.AddField(
            model_name='experiencedevelopmentstage',
            name='max_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiencedevelopmentstage',
            name='min_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiencedevelopmentstage',
            name='stage_level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_in_stage', to='user.experiencedevelopmentstage'),
        ),
    ]
