# Generated by Django 5.1.6 on 2025-02-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_experiencedevelopmentstage_next_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstreak',
            name='last_streak_update',
        ),
        migrations.AddField(
            model_name='userstreak',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
