# Generated by Django 5.1.6 on 2025-02-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_userstreak_last_streak_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstreak',
            name='current_streak',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='longest_streak',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
