# Generated by Django 5.1.6 on 2025-02-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_userstreak_current_streak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image_url',
        ),
    ]
