<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0661d5e7-a1ea-4af3-92e8-3cf82505af8d</UserSecretsId>
    <RootNamespace>ELTE.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <Company>Eötvös Loránd University (ELTE), Faculty of Informatics</Company>
    <Copyright>Copyright © ELTE Faculty of Informatics 2025</Copyright>
    <Authors>Máté Cserép, Zsombor Hartmann, Péter Kaszab, Roxána Provender</Authors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cinema.DataAccess\Cinema.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <None Update="App_Data\SampleImages\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
