# Generated by Django 5.0.6 on 2024-06-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='friends_applied',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
