# Generated by Django 5.0.6 on 2024-06-23 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_friends_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_gallery_photos', to='events.event'),
        ),
        migrations.AddField(
            model_name='photo',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_gallery_photos', to='events.event'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='events.event'),
        ),
    ]
