# Generated by Django 5.0.6 on 2024-06-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_photo_donation_photo_petition_alter_photo_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='petition',
        ),
    ]
