# Generated by Django 5.0.6 on 2025-01-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_photo_donation_remove_photo_petition"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="image_url",
            new_name="main_image_url",
        ),
    ]
