# Generated by Django 5.0.6 on 2025-01-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_rename_image_url_event_main_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="event",
        ),
    ]
