# Generated by Django 5.0.6 on 2025-01-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_photo_event"),
        ("shared", "0003_alter_team_name_photo"),
        ("user", "0002_remove_donation_impact_gallery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="gallery_photos",
            field=models.ManyToManyField(
                blank=True, related_name="event_gallery_photos", to="shared.photo"
            ),
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
