# Generated by Django 5.0.6 on 2025-01-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_gallery_photos_delete_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='friends_applied',
        ),
    ]
