# Generated by Django 5.0.6 on 2025-01-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_friends_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
