# Generated by Django 5.0.6 on 2025-01-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_achievements_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gallery_photos',
        ),
    ]
