# Generated by Django 5.0.6 on 2025-01-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_gallery_photos'),
        ('shared', '0008_achievements'),
        ('user', '0007_alter_customuser_gained_achievements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievements',
        ),
        migrations.AlterField(
            model_name='event',
            name='achievements',
            field=models.ManyToManyField(related_name='event_achv', to='shared.achievements'),
        ),
    ]
