# Generated by Django 5.0.6 on 2025-02-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_delete_achievements_alter_event_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='team',
            new_name='focus_teams',
        ),
    ]
