# Generated by Django 5.0.6 on 2025-02-16 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_team_event_focus_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRRDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bic', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient_address', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='markerType',
            field=models.IntegerField(choices=[(1, 'Volunteering opportunity'), (2, 'Sustainable event'), (3, 'Donation')]),
        ),
        migrations.AddField(
            model_name='event',
            name='donation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.trrdonation'),
        ),
    ]
