# Generated by Django 5.1.6 on 2025-02-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_trrdonation_alter_event_markertype_event_donation'),
        ('shared', '0012_rename_name_achievements_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='achievements',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_achv', to='shared.achievements'),
        ),
        migrations.AlterField(
            model_name='event',
            name='competences',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_comp', to='shared.competences'),
        ),
        migrations.AlterField(
            model_name='event',
            name='focus_teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_teams_focus', to='shared.team'),
        ),
    ]
