# Generated by Django 5.1.6 on 2025-02-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_achievements_alter_event_competences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_xp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
